# Generated by Django 2.0.6 on 2018-06-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('logo_image', models.ImageField(blank=True, upload_to='course/logo_image', verbose_name='项目logo')),
                ('file', models.FileField(blank=True, upload_to='course/file', verbose_name='文件路径')),
                ('public_type', models.SmallIntegerField(choices=[(0, '内测版'), (1, '公测版')], default=0, verbose_name='项目类型')),
                ('intro', models.CharField(max_length=1000, verbose_name='项目介绍')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App应用',
                'verbose_name_plural': 'App应用',
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='项目类别')),
                ('intro', models.CharField(blank=True, max_length=500, verbose_name='项目介绍')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '项目类别',
                'verbose_name_plural': '项目介绍',
                'db_table': 'course_category',
            },
        ),
        migrations.CreateModel(
            name='AppComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='评论内容')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('app_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.AppCategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.AppComment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目评论',
                'verbose_name_plural': '项目评论',
                'db_table': 'course_comment',
            },
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.AppCategory'),
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
